# -*- coding: utf-8 -*-
"""missing_schema.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBJf5wxRAxNME3b44IvHLtDisqey5ktw
"""

import os
import json
import zipfile
with zipfile.ZipFile('/content/schema.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

for filename in os.listdir('/content'):
    if filename.endswith(".json"): 

      with open(filename) as f:
          d = json.load(f)

      global_sch =[]
      for key in d.keys():
        for des in d[key]['description_schema']:
          global_sch.append(des)

      def getuniglobalschema(global_sch):
        global_sch_uni=[]
        global_sch_uni = set()
        for x in global_sch:
            global_sch_uni.add(x)
        global_sch_uni=list(global_sch_uni)
        return global_sch_uni

      def get_que_sch(id):
        li=[]
        for key in d.keys(): 
          if key==id:
            continue
          else:
            for qindex in range(len(d[key]['questions'])):
              li.append(d[key]['questions'][qindex]['schema'])
        return li

      missing={}
      final_missing={}
      for key in d.keys():
        dummy=[]
        copi=[]
        for des in d[key]['description_schema']:
          dummy.append(des)
          copi = getuniglobalschema(global_sch)
          for ele in copi:
            if ele in dummy:
              copi.remove(ele)
              copi=copi+get_que_sch(key)
              missing.__setitem__('schema',copi)
              final_missing.__setitem__(key,missing)
              missing={}
 

      # ds = [d, final_missing]
      # m = {}
      # for k in final_missing.keys():
      #   m[k] = tuple(m[k] for m in ds)

      ds = {}
      for final_key in d.keys():
        ds[final_key] = d[final_key]
        if(final_key) in list(final_missing.keys()):
          for key in final_missing[final_key]:
            ds[final_key][key] = final_missing[final_key][key]

      with open('missing_'+filename, "w") as outfile:
          json.dump(ds, outfile,indent =2)